### PR TITLE
add david's code

### PR DESCRIPTION
**Pull request by renaissancedog**
adding david's random code
please fix breaking changes before merge (Python script mainly)
And add better css and scripts to control it bc I’m too lazy to

### CODE REVIEW

**Comment by partywarp** [comment]
dude I give up

**Comment by partywarp** [comment]
rollback to added navbar though
I like the consistency

**Comment by renaissancedog** [comment]
fine I’ll add that tomorrow

**Comment by renaissancedog** [comment]
added navbar

**Pull request closed without merging**
